### ISSUE TITLE
Split magnitude sample via Otsu's method

### ISSUE THREAD

**Issue by hombit** [light-curve/light-curve#25]
Magnitudes are split to "high" and "low" groups, some interesting features can be extracted from these two groups: mean difference, variance ratio, count ratio, relative time duration inside each group, etc

https://en.wikipedia.org/wiki/Otsu%27s_method

See @matwey's implementation:
http://curl.sai.msu.ru/hg/home/matwey/domecam/file/tip/include/otsu.h
https://ieeexplore.ieee.org/document/9170791

**Comment by hombit** [comment]
Return at least three values: difference of subset means, standard deviation of the lower subset and standard deviation of the upper subset

**Comment by hombit** [comment]
Also consider renaming to `OtsuSplit` or something like this

**Comment by anlava** [comment]
- [ ] Change upper-to-lower observation count ratio to upper-to-all or lower-to-all
- [ ] Add description and names

**Comment by anlava** [comment]
https://github.com/light-curve/light-curve/commit/12f31f9dff8053d7488151d62b0ed919c5c0a50b and https://github.com/light-curve/light-curve/commit/0901a39be87a9b797d6769b1383e95252f1b9806
